FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_SOCKET_URL
ARG NEXT_PUBLIC_SESSION_COOKIE_NAME
ARG NEXT_PUBLIC_AUTH_REDIRECT_URL
ARG NEXT_PUBLIC_WORDS_PER_PAGE
ARG NEXT_PUBLIC_ROOT_DOMAIN
ARG ENABLE_SUBDOMAIN_ROUTING
ARG NEXT_PUBLIC_APP_ORIGIN

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL
ENV NEXT_PUBLIC_SESSION_COOKIE_NAME=$NEXT_PUBLIC_SESSION_COOKIE_NAME
ENV NEXT_PUBLIC_AUTH_REDIRECT_URL=$NEXT_PUBLIC_AUTH_REDIRECT_URL
ENV NEXT_PUBLIC_WORDS_PER_PAGE=$NEXT_PUBLIC_WORDS_PER_PAGE
ENV NEXT_PUBLIC_ROOT_DOMAIN=$NEXT_PUBLIC_ROOT_DOMAIN
ENV ENABLE_SUBDOMAIN_ROUTING=$ENABLE_SUBDOMAIN_ROUTING
ENV NEXT_PUBLIC_APP_ORIGIN=$NEXT_PUBLIC_APP_ORIGIN
ENV NODE_ENV=development

# RUN npm run build

ENV HOSTNAME=0.0.0.0
ENV PORT=3000

EXPOSE 3000

CMD ["npm", "run", "dev"]