import type { AdminTestimonialResponse, AdminTestimonialService } from "../_types/testimonials.type";

export const FALLBACK_TESTIMONIAL_SERVICES: readonly AdminTestimonialService[] = [
  { id: "service-essays", name: "Essays", slug: "essays" },
  { id: "service-data-analysis", name: "Data Analysis", slug: "data-analysis" },
  { id: "service-research", name: "Research", slug: "research" },
];

export const FALLBACK_TESTIMONIALS: readonly AdminTestimonialResponse[] = [
  {
    id: "t-1",
    user_id: "u-1",
    service_id: "service-essays",
    order_id: "order-101",
    content: "Excellent quality and extremely quick turnaround. The formatting was spot on!",
    rating: 5,
    is_approved: true,
    created_at: "2026-06-20T12:00:00Z",
    user: { id: "u-1", name: "John Doe", email: "john@example.com", avatar_url: "" },
    service: { id: "service-essays", name: "Essays", slug: "essays" },
  },
  {
    id: "t-2",
    user_id: "u-2",
    service_id: "service-data-analysis",
    order_id: "order-102",
    content: "The regression analysis was accurate and the SPSS reporting was highly descriptive.",
    rating: 4,
    is_approved: false,
    created_at: "2026-06-21T09:30:00Z",
    user: { id: "u-2", name: "Jane Smith", email: "jane@example.com", avatar_url: "" },
    service: { id: "service-data-analysis", name: "Data Analysis", slug: "data-analysis" },
  },
  {
    id: "t-3",
    user_id: "u-3",
    service_id: "service-research",
    order_id: "order-103",
    content: "Solid literature review. Some feedback was received from my advisor, but mostly good.",
    rating: 3,
    is_approved: true,
    created_at: "2026-06-18T15:45:00Z",
    user: { id: "u-3", name: "Bob Johnson", email: "bob@example.com", avatar_url: "" },
    service: { id: "service-research", name: "Research", slug: "research" },
  },
  {
    id: "t-4",
    user_id: "u-4",
    service_id: "service-essays",
    order_id: null,
    content: "Very satisfied with the customer support and essay structure.",
    rating: 5,
    is_approved: false,
    created_at: "2026-06-22T02:00:00Z",
    user: { id: "u-4", name: "Alice Brown", email: "alice@example.com", avatar_url: "" },
    service: { id: "service-essays", name: "Essays", slug: "essays" },
  },
  {
    id: "t-5",
    user_id: "u-5",
    service_id: "service-research",
    order_id: "order-105",
    content: "Formatting was slightly off, and it was delivered right at the deadline.",
    rating: 2,
    is_approved: true,
    created_at: "2026-06-15T11:20:00Z",
    user: { id: "u-5", name: "Charlie Green", email: "charlie@example.com", avatar_url: "" },
    service: { id: "service-research", name: "Research", slug: "research" },
  },
];
