import type { UserSettings } from "../_types/settings.type";

export const FALLBACK_SETTINGS: UserSettings = {
  localization: {
    language: "en",
    country_code: "US",
    timezone: "UTC",
    date_format: "MM_DD_YYYY",
    time_format: "TWELVE_HOUR",
    currency: "USD",
    number_format: "COMMA_DOT",
    week_start: "SUNDAY",
  },
  notification: {
    email_notifications: true,
    sms_notifications: false,
    push_notifications: true,
    order_updates: true,
    payment_notifications: true,
    delivery_notifications: true,
    revision_updates: true,
    extension_updates: true,
    comment_notifications: true,
    support_ticket_updates: true,
    marketing_emails: false,
    weekly_summary: false,
  },
  email: {
    newsletter: false,
    promotional_emails: false,
    product_updates: true,
    order_confirmations: true,
    payment_receipts: true,
    account_security: true,
    frequency: "INSTANT",
    daily_digest_hour: 9,
  },
  privacy: {
    profile_visibility: "PRIVATE",
    show_email: false,
    show_phone: false,
    show_name: true,
    allow_messages: true,
    allow_comments: true,
    data_sharing: false,
    analytics_tracking: true,
    third_party_cookies: false,
    allow_search_engine_indexing: false,
  },
  accessibility: {
    font_size_multiplier: 1.0,
    text_spacing_increased: false,
    high_contrast_mode: false,
    color_blind_mode: false,
    reduced_motion: false,
    screen_reader_optimized: false,
    keyboard_navigation_enhanced: false,
    focus_indicators_enhanced: false,
  },
  billing: {
    invoice_email: null,
    invoice_delivery: "EMAIL",
    payment_reminders: true,
    reminder_days_before: 3,
    auto_reload_enabled: false,
    auto_reload_threshold: null,
  },
};
