import type {
  ServiceCategory,
  Sample,
  BlogPostResponse,
} from "../_types";

export const FALLBACK_FEATURED_SERVICES: ServiceCategory[] = [
  {
    id:                  "proofreading-editing",
    name:                "Proofreading and Editing",
    description:         "Whether it is an academic paper, resume, or business document, professional proofreading helps.",
    order:                1,
  },
  {
    id:                  "essay-writing",
    name:                "Essay Writing",
    description:         "From essays and dissertations to admission papers, we support you in producing structured papers.",
    order:                2,
  },
  {
    id:                  "data-analysis",
    name:                "Data Analysis",
    description:         "Make sense of your data and uncover key insights with accurate analysis, visualizations, and conclusions.",
    order:                3,
  },
  {
    id:                  "presentations",
    name:                "Presentations",
    description:         "Impress your audience with professionally designed slides and compelling narratives.",
    order:                4,
  },
  {
    id:                  "research",
    name:                "Research",
    description:         "Thorough literature reviews, annotated bibliographies, and structured research support.",
    order:                5,
  },
  {
    id:                  "coding-programming",
    name:                "Coding & Programming",
    description:         "Get help with technical assignments, debugging, and code documentation.",
    order:                6,
  },
];

export const FALLBACK_SAMPLES: Sample[] = [
  {
    id:         "sample-1",
    title:      "Argumentative Essay on Climate Change",
    slug:       "argumentative-essay-climate-change",
    excerpt:    "A compelling argumentative essay exploring the human impact on global climate patterns, featuring rigorous citations and structured reasoning.",
    service_id: "essay-writing",
    word_count: 1250,
    featured:   true,
    image:      "https://placehold.co/600x400/1a1a1a/ffffff?text=Climate+Essay",
    tags:       [{ id: "t1", name: "Essay", description: "Essay writing", slug: "essay", usage_count: 1 }],
  },
  {
    id:         "sample-2",
    title:      "Business Plan: SaaS Startup",
    slug:       "business-plan-saas-startup",
    excerpt:    "A comprehensive business plan for a B2B SaaS product, covering market analysis, financial projections, and go-to-market strategy.",
    service_id: "research",
    word_count: 3400,
    featured:   true,
    image:      "https://placehold.co/600x400/1a1a1a/ffffff?text=Business+Plan",
    tags:       [{ id: "t2", name: "Business", description: "Business writing", slug: "business", usage_count: 1 }],
  },
  {
    id:         "sample-3",
    title:      "Data Visualisation Report: Sales Trends",
    slug:       "data-visualisation-sales-trends",
    excerpt:    "A detailed analytical report with charts and statistical breakdowns of quarterly sales trends across multiple regions.",
    service_id: "data-analysis",
    word_count: 2100,
    featured:   true,
    image:      "https://placehold.co/600x400/1a1a1a/ffffff?text=Data+Report",
    tags:       [{ id: "t3", name: "Analysis", description: "Data analysis", slug: "analysis", usage_count: 1 }],
  },
  {
    id:         "sample-4",
    title:      "Literature Review: AI in Healthcare",
    slug:       "literature-review-ai-healthcare",
    excerpt:    "A systematic literature review of peer-reviewed papers on the application of artificial intelligence in clinical diagnostics.",
    service_id: "research",
    word_count: 4200,
    featured:   false,
    image:      "https://placehold.co/600x400/1a1a1a/ffffff?text=Literature+Review",
    tags:       [{ id: "t4", name: "Research", description: "Research writing", slug: "research", usage_count: 1 }],
  },
];

export const FALLBACK_BLOGS: BlogPostResponse[] = [
  {
    id:               "blog-1",
    title:            "How to Write a First-Class Dissertation",
    content:          "A complete walkthrough of structuring, researching, and writing a dissertation that stands out to examiners.",
    author:           "Dr. Sarah Ochieng",
    category_id:      "academic-writing",
    slug:             "how-to-write-first-class-dissertation",
    excerpt:          "A complete walkthrough of structuring, researching, and writing a dissertation that stands out to examiners.",
    featured_image:   "https://placehold.co/600x400/1a1a1a/ffffff?text=Dissertation+Guide",
    meta_description: "Learn how to write a first-class dissertation with expert tips on structure, research, and writing.",
    is_published:     true,
    is_featured:      true,
    published_at:     "2026-02-14T08:00:00.000Z",
    tags:             [{ id: "t5", name: "Dissertation", description: "Dissertation tips", slug: "dissertation", usage_count: 12 }],
  },
  {
    id:               "blog-2",
    title:            "5 Common Proofreading Mistakes and How to Avoid Them",
    content:          "Even experienced writers overlook these five critical proofreading errors. Here is how to catch them every time.",
    author:           "James Kariuki",
    category_id:      "proofreading",
    slug:             "common-proofreading-mistakes",
    excerpt:          "Even experienced writers overlook these five critical proofreading errors. Here is how to catch them every time.",
    featured_image:   "https://placehold.co/600x400/1a1a1a/ffffff?text=Proofreading+Tips",
    meta_description: "Avoid the five most common proofreading mistakes with actionable tips from professional editors.",
    is_published:     true,
    is_featured:      true,
    published_at:     "2026-01-28T10:30:00.000Z",
    tags:             [{ id: "t6", name: "Proofreading", description: "Proofreading tips", slug: "proofreading", usage_count: 8 }],
  },
  {
    id:               "blog-3",
    title:            "APA vs MLA: Which Citation Style Should You Use?",
    content:          "A side-by-side comparison of APA and MLA citation formats, with practical guidance on when to use each.",
    author:           "Amina Waweru",
    category_id:      "academic-writing",
    slug:             "apa-vs-mla-citation-guide",
    excerpt:          "A side-by-side comparison of APA and MLA citation formats, with practical guidance on when to use each.",
    featured_image:   "https://placehold.co/600x400/1a1a1a/ffffff?text=Citation+Guide",
    meta_description: "APA vs MLA: understand the key differences and choose the right citation style for your paper.",
    is_published:     true,
    is_featured:      false,
    published_at:     "2026-01-10T09:00:00.000Z",
    tags:             [{ id: "t7", name: "Citations", description: "Citation styles", slug: "citations", usage_count: 6 }],
  },
];
